#Requires -Version 5.1
<#
.SYNOPSIS
    Safely uninstalls the PowerShell Profile ecosystem.
.DESCRIPTION
    Cross-platform uninstaller with:
    - Safe symlink removal (only removes links created by this project)
    - Automatic backup detection and restoration
    - Plugin cache cleanup
    - Clear guidance for manual cleanup steps
    - Never deletes files that don't belong to this project
.EXAMPLE
    .\uninstall.ps1
.NOTES
    Revision: 05/2026 | License: MIT
#>

# ── STRICT MODE ──────────────────────────────────────────────
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# ── SHARED LIBS ──────────────────────────────────────────────
. (Join-Path $PSScriptRoot 'lib/platform.ps1')
. (Join-Path $PSScriptRoot 'lib/ux-helpers.ps1')
. (Join-Path $PSScriptRoot 'lib/profile-paths.ps1')

# ── RESOLVE PATHS ────────────────────────────────────────────
$script:SourceProfile = Join-Path $PSScriptRoot 'Microsoft.PowerShell_profile.ps1'

# Resolve target profile path (cross-platform) — loaded from lib/profile-paths.ps1

$script:TargetProfile = script:Get-TargetProfilePath
$script:TargetDir     = Split-Path $script:TargetProfile -Parent

# ══════════════════════════════════════════════════════════════
# BANNER
# ══════════════════════════════════════════════════════════════
Write-Host ""
Write-Host "  ╔══════════════════════════════════════════════╗" -ForegroundColor Cyan
Write-Host "  ║   PowerShell Profile Uninstaller v2.0       ║" -ForegroundColor Cyan
Write-Host "  ║   Windows 10+ / Linux (Fedora)              ║" -ForegroundColor Cyan
Write-Host "  ╚══════════════════════════════════════════════╝" -ForegroundColor Cyan
Write-Host ""

$platform = if ($script:IsWin) { "Windows" } else { "Linux" }
Write-Info "Platform: $platform | PS $($PSVersionTable.PSVersion)"
Write-Info "Profile:  $script:TargetProfile"
Write-Host ""

# ══════════════════════════════════════════════════════════════
# STEP 1: VALIDATE WHAT EXISTS
# ══════════════════════════════════════════════════════════════
Write-Host "  [1/4] Analyzing current installation..." -ForegroundColor Cyan

$script:ProfileExists   = Test-Path $script:TargetProfile
$script:IsOurSymlink    = $false
$script:IsOtherFile     = $false

if ($script:ProfileExists) {
    $item = Get-Item $script:TargetProfile -Force -ErrorAction SilentlyContinue

    $content = Get-Content $script:TargetProfile -Raw -ErrorAction SilentlyContinue
    if ($content -match "\. `"[^`"]*Microsoft\.PowerShell_profile\.ps1`"") {
        $script:IsOurSymlink = $true
        Write-Ok "Found profile generated by this project."
        Write-Info "→ $script:TargetProfile"
    } else {
        $script:IsOtherFile = $true
        Write-Warn "Found a regular profile file, but it was NOT generated by this project."
        Write-Info "Size: $($item.Length) bytes | Modified: $($item.LastWriteTime)"
    }
} else {
    Write-Info "No profile found at target path. Nothing to remove."
}

# ══════════════════════════════════════════════════════════════
# STEP 2: REMOVE PROFILE SYMLINK
# ══════════════════════════════════════════════════════════════
Write-Host "  [2/4] Removing profile..." -ForegroundColor Cyan

if ($script:IsOurSymlink) {
    try {
        Remove-Item $script:TargetProfile -Force -ErrorAction Stop
        Write-Ok "Profile removed: $script:TargetProfile"
    } catch {
        Write-Fail "Failed to remove profile: $($_.Exception.Message)"
    }
} elseif ($script:IsOtherFile) {
    Write-Warn "Profile at $script:TargetProfile was NOT created by this project."
    Write-Warn "Skipping removal to avoid data loss."
    Write-Info "To remove manually: Remove-Item '$script:TargetProfile' -Force"
} else {
    Write-Ok "No profile to remove."
}

# ══════════════════════════════════════════════════════════════
# STEP 3: RESTORE BACKUP
# ══════════════════════════════════════════════════════════════
Write-Host "  [3/4] Checking for backups..." -ForegroundColor Cyan

# Find all backups sorted by date (newest first)
$backups = @(Get-ChildItem -Path $script:TargetDir -Filter "Microsoft.PowerShell_profile.ps1.bak*" -ErrorAction SilentlyContinue |
    Sort-Object LastWriteTime -Descending)

if ($backups.Count -gt 0) {
    Write-Ok "Found $($backups.Count) backup(s):"
    $i = 1
    foreach ($bak in $backups) {
        $size = [math]::Round($bak.Length / 1KB, 1)
        Write-Info "  [$i] $($bak.Name) (${size}KB, $($bak.LastWriteTime.ToString('yyyy-MM-dd HH:mm:ss')))"
        $i++
    }

    # Only offer restore if we actually removed the profile
    if ($script:IsOurSymlink -or -not $script:ProfileExists) {
        Write-Host ""
        Write-Host "  Restore a backup? Enter number (1-$($backups.Count)), or N to skip: " -NoNewline -ForegroundColor Yellow
        $choice = Read-Host

        if ($choice -match '^\d+$') {
            $idx = [int]$choice - 1
            if ($idx -ge 0 -and $idx -lt $backups.Count) {
                $selectedBackup = $backups[$idx]
                try {
                    Copy-Item $selectedBackup.FullName $script:TargetProfile -Force -ErrorAction Stop
                    Write-Ok "Restored: $($selectedBackup.Name) → $script:TargetProfile"

                    Write-Host "  Delete this backup file? [y/N]: " -NoNewline -ForegroundColor Yellow
                    $delChoice = Read-Host
                    if ($delChoice -eq 'y') {
                        Remove-Item $selectedBackup.FullName -Force
                        Write-Ok "Backup deleted."
                    }
                } catch {
                    Write-Fail "Failed to restore backup: $($_.Exception.Message)"
                }
            } else {
                Write-Warn "Invalid selection. Skipping restore."
            }
        } else {
            Write-Info "Skipping backup restoration."
        }
    } else {
        Write-Info "Profile was not removed (not ours), skipping restore offer."
    }
} else {
    Write-Info "No backups found."
}

# ══════════════════════════════════════════════════════════════
# STEP 4: CLEANUP CACHE FILES
# ══════════════════════════════════════════════════════════════
Write-Host "  [4/4] Cleaning up cache files..." -ForegroundColor Cyan

# All possible cache locations
$cacheLocations = @(
    (Join-Path $HOME '.cache_pwsh_plugins.ps1')
)

# XDG cache path
$xdgCache = $env:XDG_CACHE_HOME
if (-not $xdgCache) { $xdgCache = Join-Path $HOME '.cache' }
$xdgCacheFile = Join-Path (Join-Path $xdgCache 'pwsh') 'plugins_cache.ps1'
$cacheLocations += $xdgCacheFile

$cacheCleaned = 0
foreach ($cachePath in $cacheLocations) {
    if (Test-Path $cachePath) {
        try {
            Remove-Item $cachePath -Force -ErrorAction Stop
            Write-Ok "Cache removed: $cachePath"
            $cacheCleaned++
        } catch {
            Write-Warn "Could not remove cache: $cachePath"
        }
    }
}

# Clean empty XDG pwsh cache directory
$xdgPwshDir = Join-Path $xdgCache 'pwsh'
if ((Test-Path $xdgPwshDir) -and (Get-ChildItem $xdgPwshDir -ErrorAction SilentlyContinue).Count -eq 0) {
    Remove-Item $xdgPwshDir -Force -ErrorAction SilentlyContinue
    Write-Info "Removed empty cache directory: $xdgPwshDir"
}

if ($cacheCleaned -eq 0) {
    Write-Info "No cache files found."
}

# ══════════════════════════════════════════════════════════════
# SUMMARY & MANUAL CLEANUP GUIDANCE
# ══════════════════════════════════════════════════════════════
Write-Host ""
Write-Host "  ╔══════════════════════════════════════════════╗" -ForegroundColor Green
Write-Host "  ║   ✔ Uninstallation Complete                 ║" -ForegroundColor Green
Write-Host "  ╚══════════════════════════════════════════════╝" -ForegroundColor Green
Write-Host ""
Write-Host "  Optional manual cleanup:" -ForegroundColor White
Write-Host ""
Write-Info "Remove optional modules (if no longer needed):"
Write-Info "  Uninstall-Module Terminal-Icons -Force"
Write-Info "  Uninstall-Module PSReadLine -Force"
Write-Host ""
Write-Info "Remove optional tools:"
if ($script:IsWin) {
    Write-Info "  winget uninstall JanDeDobbeleer.OhMyPosh"
    Write-Info "  winget uninstall ajeetdsouza.zoxide"
} else {
    Write-Info "  sudo dnf remove oh-my-posh zoxide  # or equivalent"
}
Write-Host ""
Write-Info "Remaining backups (if any):"
$remainingBackups = @(Get-ChildItem -Path $script:TargetDir -Filter "*.bak*" -ErrorAction SilentlyContinue)
if ($remainingBackups.Count -gt 0) {
    foreach ($b in $remainingBackups) {
        Write-Info "  $($b.FullName)"
    }
} else {
    Write-Info "  None."
}
Write-Host ""
Write-Host "  Restart your terminal to complete." -ForegroundColor White
Write-Host ""

if ($Host.Name -match 'ConsoleHost') {
    Write-Host "Press any key to exit..." -ForegroundColor DarkGray
    $null = $Host.UI.RawUI.ReadKey('NoEcho,IncludeKeyDown')
}


