#Requires -Version 5.1
# Profile install/uninstall

function Get-ProfilePath {
    if ($PROFILE) {
        $allHosts = $PROFILE.PSObject.Properties['CurrentUserAllHosts']
        if ($allHosts -and $allHosts.Value) {
            return $allHosts.Value
        }
    }
    return $PROFILE
}

function ConvertTo-PowerShellLiteral {
    param([AllowEmptyString()][string]$Value)
    return "'$($Value.Replace("'", "''"))'"
}

function Get-LegacyProfileContent {
    param([AllowEmptyString()][string]$Content)

    $lines = @($Content -split '\r?\n')
    $remove = @{}
    for ($index = 0; $index -lt $lines.Count - 2; $index++) {
        if ($lines[$index] -notmatch '^# Generated by config-powershell7 installer\s*$') { continue }
        $root = $null
        if ($lines[$index + 1] -match '^\$env:__PROFILE_REPO_ROOT\s*=\s*''((?:[^'']|'''')*)''\s*$') {
            $root = $Matches[1].Replace("''", "'")
        } elseif ($lines[$index + 1] -match '^\$env:__PROFILE_REPO_ROOT\s*=\s*"([^"`$]+)"\s*$') {
            $root = $Matches[1]
        }
        if (-not $root) { continue }
        $source = Join-Path $root 'Microsoft.PowerShell_profile.ps1'
        $sourceLine = $index + 2
        if ($lines[$sourceLine] -match '^\$env:(?:POSH_THEME|CONFIG_PWSH7_THEME)\s*=') { $sourceLine++ }
        if ($sourceLine -ge $lines.Count) { continue }
        $singleQuoted = [regex]::Escape((ConvertTo-PowerShellLiteral $source))
        $doubleQuoted = [regex]::Escape('"' + $source + '"')
        if ($lines[$sourceLine] -notmatch "^\.\s+(?:$singleQuoted|$doubleQuoted)\s*$") { continue }
        # Only remove the contiguous generated stub whose source matches its
        # declared repo. Unrelated dot-sources and user environment settings stay.
        for ($owned = $index; $owned -le $sourceLine; $owned++) { $remove[$owned] = $true }
        $index = $sourceLine
    }
    $remaining = if ($remove.Count -gt 0) {
        (@(for ($index = 0; $index -lt $lines.Count; $index++) {
            if (-not $remove.ContainsKey($index)) { $lines[$index] }
        })) -join "`r`n"
    } else { $Content }
    return [PSCustomObject]@{ Found = $remove.Count -gt 0; Content = $remaining }
}

function Remove-LegacyCurrentHostProfile {
    $hostProperty = $PROFILE.PSObject.Properties['CurrentUserCurrentHost']
    if (-not $hostProperty -or -not $hostProperty.Value -or $hostProperty.Value -eq (Get-ProfilePath)) { return }
    $hostPath = $hostProperty.Value
    if (-not (Test-Path -LiteralPath $hostPath -PathType Leaf)) { return }
    $legacy = Get-LegacyProfileContent -Content (Get-Content -LiteralPath $hostPath -Raw -ErrorAction Stop)
    if (-not $legacy.Found) { return }
    $backup = "$hostPath.bak-$([guid]::NewGuid().ToString('N'))"
    Copy-Item -LiteralPath $hostPath -Destination $backup -ErrorAction Stop
    if ([string]::IsNullOrWhiteSpace($legacy.Content)) {
        Remove-Item -LiteralPath $hostPath -Force -ErrorAction Stop
    } else {
        Set-Content -LiteralPath $hostPath -Value $legacy.Content -Encoding UTF8 -NoNewline -Force -ErrorAction Stop
    }
    Write-GuiLog "Legacy current-host stub removed; backup retained at: $backup" -Type Info
}

function Install-Profile {
    param(
        [string]$RepoPath,
        [string]$ThemeName = ''
    )

    if (-not (Test-Path -LiteralPath $RepoPath -PathType Container)) {
        Write-GuiLog "Repository path not found: $RepoPath" -Type Fail
        return $false
    }

    $RepoPath = (Resolve-Path -LiteralPath $RepoPath -ErrorAction Stop).ProviderPath
    $sourceProfile = Join-Path $RepoPath 'Microsoft.PowerShell_profile.ps1'
    $sourceModules = Join-Path $RepoPath 'modules'
    $targetProfile = Get-ProfilePath

    if (-not $targetProfile) {
        Write-GuiLog "Cannot determine profile path. `$PROFILE is not set." -Type Fail
        return $false
    }

    $targetDir = Split-Path $targetProfile -Parent

    if (-not (Test-Path -LiteralPath $sourceProfile -PathType Leaf)) {
        Write-GuiLog "Profile source not found: $sourceProfile" -Type Fail
        return $false
    }
    if (-not (Test-Path -LiteralPath $sourceModules -PathType Container)) {
        Write-GuiLog "Modules directory not found: $sourceModules" -Type Fail
        return $false
    }

    Write-GuiLog "Linking profile..." -Type Step

    if (-not (Test-Path -LiteralPath $targetDir)) {
        New-Item -ItemType Directory -Force -Path $targetDir | Out-Null
    }

    $beginMarker = '# >>> config-powershell7 >>>'
    $endMarker = '# <<< config-powershell7 <<<'
    $sourceLiteral = ConvertTo-PowerShellLiteral $sourceProfile
    $managedLines = @($beginMarker, '# Managed by config-powershell7. Changes inside this block are replaced.')
    if ($ThemeName) {
        $managedLines += "`$env:CONFIG_PWSH7_THEME = $(ConvertTo-PowerShellLiteral $ThemeName)"
    }
    $managedLines += ". $sourceLiteral"
    $managedLines += $endMarker
    $managedBlock = $managedLines -join "`r`n"

    $existingContent = if (Test-Path -LiteralPath $targetProfile) {
        Get-Content -LiteralPath $targetProfile -Raw -ErrorAction Stop
    } else { '' }
    if ($null -eq $existingContent) { $existingContent = '' }

    $managedPattern = '(?ms)^# >>> config-powershell7 >>>\r?\n.*?^# <<< config-powershell7 <<<(?=\r?$)'
    $legacy = Get-LegacyProfileContent -Content $existingContent
    $legacyOwned = $legacy.Found -and [string]::IsNullOrWhiteSpace($legacy.Content)

    if ($existingContent -match $managedPattern) {
        # A replacement string interprets $$, $& and $' as regex tokens. Paths
        # and theme literals must be inserted verbatim, including dollar signs.
        $newContent = [regex]::Replace($existingContent, $managedPattern, [System.Text.RegularExpressions.MatchEvaluator]{ param($match) $managedBlock })
    } elseif ($legacyOwned) {
        $newContent = $managedBlock + "`r`n"
    } elseif ($legacy.Found) {
        $newContent = $legacy.Content + "`r`n" + $managedBlock + "`r`n"
    } elseif ([string]::IsNullOrWhiteSpace($existingContent)) {
        $newContent = $managedBlock + "`r`n"
    } else {
        $separator = if ($existingContent.EndsWith("`n")) { "`r`n" } else { "`r`n`r`n" }
        $newContent = $existingContent + $separator + $managedBlock + "`r`n"
    }

    if ($newContent -ceq $existingContent) {
        Remove-LegacyCurrentHostProfile
        Write-GuiLog "Profile already correctly linked." -Type Ok
        return $true
    }

    if ($existingContent -and -not $legacyOwned -and $existingContent -notmatch $managedPattern) {
        $timestamp = Get-Date -Format 'yyyyMMdd-HHmmss'
        $backupPath = "$targetProfile.bak-$timestamp"
        while (Test-Path -LiteralPath $backupPath) {
            $backupPath = "$targetProfile.bak-$timestamp-$(Get-Random -Maximum 9999)"
        }
        Copy-Item -LiteralPath $targetProfile -Destination $backupPath -Force
        Write-GuiLog "Existing profile backed up: $backupPath" -Type Info
    }

    Set-Content -LiteralPath $targetProfile -Value $newContent -Encoding UTF8 -NoNewline -Force -ErrorAction Stop

    $content = Get-Content -LiteralPath $targetProfile -Raw -ErrorAction Stop
    if ($content -match $managedPattern -and $content.Contains($sourceLiteral)) {
        Remove-LegacyCurrentHostProfile
        Write-GuiLog "Profile linked successfully!" -Type Ok
        return $true
    } else {
        Write-GuiLog "Profile link validation failed." -Type Fail
        return $false
    }
}

function Uninstall-Profile {
    param([string]$RepoPath)

    $targetProfile = Get-ProfilePath

    if (-not $targetProfile) {
        Write-GuiLog "Cannot determine profile path. `$PROFILE is not set." -Type Fail
        return $false
    }

    $targetDir = Split-Path $targetProfile -Parent

    Write-GuiLog "Analyzing current installation..." -Type Step

    if (Test-Path -LiteralPath $targetProfile) {
        $content = Get-Content -LiteralPath $targetProfile -Raw -ErrorAction Stop
        $managedPattern = '(?ms)^# >>> config-powershell7 >>>\r?\n.*?^# <<< config-powershell7 <<<\r?(?:\n)?'
        $legacy = Get-LegacyProfileContent -Content $content
        if ($content -match $managedPattern) {
            Write-GuiLog "Found managed profile block." -Type Ok
            $remaining = [regex]::Replace($content, $managedPattern, '')
            if (-not [string]::IsNullOrWhiteSpace($remaining)) {
                Set-Content -LiteralPath $targetProfile -Value $remaining -Encoding UTF8 -NoNewline -Force -ErrorAction Stop
            } else {
                Remove-Item -LiteralPath $targetProfile -Force -ErrorAction Stop
            }
            Write-GuiLog "Managed profile block removed." -Type Ok
        } elseif ($legacy.Found) {
            Write-GuiLog "Found legacy profile created by this project." -Type Ok
            if ([string]::IsNullOrWhiteSpace($legacy.Content)) {
                Remove-Item -LiteralPath $targetProfile -Force -ErrorAction Stop
            } else {
                Copy-Item -LiteralPath $targetProfile -Destination "$targetProfile.bak-$([guid]::NewGuid().ToString('N'))" -ErrorAction Stop
                Set-Content -LiteralPath $targetProfile -Value $legacy.Content -Encoding UTF8 -NoNewline -Force -ErrorAction Stop
            }
            Write-GuiLog "Legacy profile removed." -Type Ok
        } else {
            Write-GuiLog "Profile exists but was NOT created by this project - skipping removal." -Type Warn
        }
    } else {
        Write-GuiLog "No profile found. Nothing to remove." -Type Info
    }

    Remove-LegacyCurrentHostProfile
    $backupFilter = (Split-Path $targetProfile -Leaf) + '.bak*'
    $backups = @(Get-ChildItem -LiteralPath $targetDir -Filter $backupFilter -ErrorAction SilentlyContinue |
        Sort-Object LastWriteTime -Descending)
    if ($backups.Count -gt 0) {
        Write-GuiLog "Found $($backups.Count) backup file(s)." -Type Info
    }

    Write-GuiLog "Cleaning up cache files..." -Type Step
    $cachePaths = @(
        (Join-Path $HOME '.cache_pwsh_plugins.ps1')
    )
    $xdgCache = if ($env:XDG_CACHE_HOME) { $env:XDG_CACHE_HOME } else { Join-Path $HOME '.cache' }
    $cachePaths += Join-Path (Join-Path $xdgCache 'pwsh') 'plugins_cache.ps1'

    foreach ($cachePath in $cachePaths) {
        if (Test-Path -LiteralPath $cachePath) {
            Remove-Item -LiteralPath $cachePath -Force -ErrorAction SilentlyContinue
            Write-GuiLog "Cache removed: $cachePath" -Type Ok
        }
    }

    $xdgPwshDir = Join-Path $xdgCache 'pwsh'
    if ((Test-Path -LiteralPath $xdgPwshDir) -and @(Get-ChildItem -LiteralPath $xdgPwshDir -ErrorAction SilentlyContinue).Count -eq 0) {
        Remove-Item -LiteralPath $xdgPwshDir -Force -ErrorAction SilentlyContinue
    }

    Write-GuiLog "Uninstallation complete." -Type Ok
    return $true
}
