#Requires -Version 5.1
# Profile install/uninstall

function Get-ProfilePath {
    if ($PROFILE) {
        $allHosts = $PROFILE.PSObject.Properties['CurrentUserAllHosts']
        if ($allHosts -and $allHosts.Value) {
            return $allHosts.Value
        }
    }
    return $PROFILE
}

function ConvertTo-PowerShellLiteral {
    param([AllowEmptyString()][string]$Value)
    return "'$($Value.Replace("'", "''"))'"
}

function Install-Profile {
    param(
        [string]$RepoPath,
        [string]$ThemeName = ''
    )

    if (-not (Test-Path $RepoPath)) {
        Write-GuiLog "Repository path not found: $RepoPath" -Type Fail
        return $false
    }

    $sourceProfile = Join-Path $RepoPath 'Microsoft.PowerShell_profile.ps1'
    $sourceModules = Join-Path $RepoPath 'modules'
    $targetProfile = Get-ProfilePath

    if (-not $targetProfile) {
        Write-GuiLog "Cannot determine profile path. `$PROFILE is not set." -Type Fail
        return $false
    }

    $targetDir = Split-Path $targetProfile -Parent

    if (-not (Test-Path $sourceProfile)) {
        Write-GuiLog "Profile source not found: $sourceProfile" -Type Fail
        return $false
    }
    if (-not (Test-Path $sourceModules)) {
        Write-GuiLog "Modules directory not found: $sourceModules" -Type Fail
        return $false
    }

    Write-GuiLog "Linking profile..." -Type Step

    if (-not (Test-Path $targetDir)) {
        New-Item -ItemType Directory -Force -Path $targetDir | Out-Null
    }

    $beginMarker = '# >>> config-powershell7 >>>'
    $endMarker = '# <<< config-powershell7 <<<'
    $sourceLiteral = ConvertTo-PowerShellLiteral $sourceProfile
    $managedLines = @($beginMarker, '# Managed by config-powershell7. Changes inside this block are replaced.')
    if ($ThemeName) {
        $managedLines += "`$env:POSH_THEME = $(ConvertTo-PowerShellLiteral $ThemeName)"
    }
    $managedLines += ". $sourceLiteral"
    $managedLines += $endMarker
    $managedBlock = $managedLines -join "`r`n"

    $existingContent = if (Test-Path $targetProfile) {
        Get-Content $targetProfile -Raw -ErrorAction SilentlyContinue
    } else { '' }
    if ($null -eq $existingContent) { $existingContent = '' }

    $managedPattern = '(?ms)^# >>> config-powershell7 >>>\r?\n.*?^# <<< config-powershell7 <<<(?=\r?$)'
    $legacyHeader = $existingContent -match '(?m)^# Generated by config-powershell7 installer\s*$'
    $legacyLines = @($existingContent -split '\r?\n' | Where-Object {
        $_ -and $_ -notmatch '^# Generated by config-powershell7 installer\s*$' -and
        $_ -notmatch '^\$env:__PROFILE_REPO_ROOT\s*=' -and
        $_ -notmatch '^\$env:POSH_THEME\s*=' -and
        $_ -notmatch '^\.\s+["''][^"'']*Microsoft\.PowerShell_profile\.ps1["'']\s*$'
    })
    $legacyOwned = $legacyHeader -and $legacyLines.Count -eq 0

    if ($existingContent -match $managedPattern) {
        $newContent = [regex]::Replace($existingContent, $managedPattern, $managedBlock)
    } elseif ($legacyOwned) {
        $newContent = $managedBlock + "`r`n"
    } elseif ($legacyHeader) {
        $preservedLegacyContent = $legacyLines -join "`r`n"
        $newContent = $preservedLegacyContent + "`r`n" + $managedBlock + "`r`n"
    } elseif ([string]::IsNullOrWhiteSpace($existingContent)) {
        $newContent = $managedBlock + "`r`n"
    } else {
        $separator = if ($existingContent.EndsWith("`n")) { "`r`n" } else { "`r`n`r`n" }
        $newContent = $existingContent + $separator + $managedBlock + "`r`n"
    }

    if ($newContent -ceq $existingContent) {
        Write-GuiLog "Profile already correctly linked." -Type Ok
        return $true
    }

    if ($existingContent -and -not $legacyOwned -and $existingContent -notmatch $managedPattern) {
        $timestamp = Get-Date -Format 'yyyyMMdd-HHmmss'
        $backupPath = "$targetProfile.bak-$timestamp"
        while (Test-Path $backupPath) {
            $backupPath = "$targetProfile.bak-$timestamp-$(Get-Random -Maximum 9999)"
        }
        Copy-Item $targetProfile $backupPath -Force
        Write-GuiLog "Existing profile backed up: $backupPath" -Type Info
    }

    Set-Content -Path $targetProfile -Value $newContent -Encoding UTF8 -NoNewline -Force

    $content = Get-Content $targetProfile -Raw -ErrorAction SilentlyContinue
    if ($content -match $managedPattern -and $content.Contains($sourceLiteral)) {
        Write-GuiLog "Profile linked successfully!" -Type Ok
        return $true
    } else {
        Write-GuiLog "Profile link validation failed." -Type Fail
        return $false
    }
}

function Uninstall-Profile {
    param([string]$RepoPath)

    $targetProfile = Get-ProfilePath

    if (-not $targetProfile) {
        Write-GuiLog "Cannot determine profile path. `$PROFILE is not set." -Type Fail
        return $false
    }

    $targetDir = Split-Path $targetProfile -Parent

    Write-GuiLog "Analyzing current installation..." -Type Step

    if (Test-Path $targetProfile) {
        $content = Get-Content $targetProfile -Raw -ErrorAction SilentlyContinue
        $managedPattern = '(?ms)^# >>> config-powershell7 >>>\r?\n.*?^# <<< config-powershell7 <<<\r?(?:\n)?'
        $legacyHeader = $content -match '(?m)^# Generated by config-powershell7 installer\s*$'
        $legacyExtraLines = @($content -split '\r?\n' | Where-Object {
            $_ -and $_ -notmatch '^# Generated by config-powershell7 installer\s*$' -and
            $_ -notmatch '^\$env:__PROFILE_REPO_ROOT\s*=' -and
            $_ -notmatch '^\$env:POSH_THEME\s*=' -and
            $_ -notmatch '^\.\s+["''][^"'']*Microsoft\.PowerShell_profile\.ps1["'']\s*$'
        })
        $legacyOwned = $legacyHeader -and $legacyExtraLines.Count -eq 0
        if ($content -match $managedPattern) {
            Write-GuiLog "Found managed profile block." -Type Ok
            $remaining = [regex]::Replace($content, $managedPattern, '')
            if (-not [string]::IsNullOrWhiteSpace($remaining)) {
                Set-Content -Path $targetProfile -Value $remaining -Encoding UTF8 -NoNewline -Force
            } else {
                Remove-Item $targetProfile -Force -ErrorAction Stop
            }
            Write-GuiLog "Managed profile block removed." -Type Ok
        } elseif ($legacyOwned) {
            Write-GuiLog "Found legacy profile created by this project." -Type Ok
            Remove-Item $targetProfile -Force -ErrorAction Stop
            Write-GuiLog "Legacy profile removed." -Type Ok
        } else {
            Write-GuiLog "Profile exists but was NOT created by this project - skipping removal." -Type Warn
        }
    } else {
        Write-GuiLog "No profile found. Nothing to remove." -Type Info
    }

    $backups = @(Get-ChildItem -Path $targetDir -Filter 'Microsoft.PowerShell_profile.ps1.bak*' -ErrorAction SilentlyContinue |
        Sort-Object LastWriteTime -Descending)
    if ($backups.Count -gt 0) {
        Write-GuiLog "Found $($backups.Count) backup file(s)." -Type Info
    }

    Write-GuiLog "Cleaning up cache files..." -Type Step
    $cachePaths = @(
        (Join-Path $HOME '.cache_pwsh_plugins.ps1')
    )
    $xdgCache = if ($env:XDG_CACHE_HOME) { $env:XDG_CACHE_HOME } else { Join-Path $HOME '.cache' }
    $cachePaths += Join-Path (Join-Path $xdgCache 'pwsh') 'plugins_cache.ps1'

    foreach ($cachePath in $cachePaths) {
        if (Test-Path $cachePath) {
            Remove-Item $cachePath -Force -ErrorAction SilentlyContinue
            Write-GuiLog "Cache removed: $cachePath" -Type Ok
        }
    }

    $xdgPwshDir = Join-Path $xdgCache 'pwsh'
    if ((Test-Path $xdgPwshDir) -and (Get-ChildItem $xdgPwshDir -ErrorAction SilentlyContinue).Count -eq 0) {
        Remove-Item $xdgPwshDir -Force -ErrorAction SilentlyContinue
    }

    Write-GuiLog "Uninstallation complete." -Type Ok
    return $true
}
