#Requires -Version 5.1
# Profile install/uninstall

function Get-ProfilePath {
    if ($PROFILE -is [string] -and $PROFILE) {
        return $PROFILE
    }
    if ($PROFILE -and $PROFILE.CurrentUserCurrentHost) {
        return $PROFILE.CurrentUserCurrentHost
    }
    return $PROFILE
}

function Install-Profile {
    param(
        [string]$RepoPath,
        [string]$ThemeName = ''
    )

    if (-not (Test-Path $RepoPath)) {
        Write-GuiLog "Repository path not found: $RepoPath" -Type Fail
        return $false
    }

    $sourceProfile = Join-Path $RepoPath 'Microsoft.PowerShell_profile.ps1'
    $sourceModules = Join-Path $RepoPath 'modules'
    $targetProfile = Get-ProfilePath

    if (-not $targetProfile) {
        Write-GuiLog "Cannot determine profile path. `$PROFILE is not set." -Type Fail
        return $false
    }

    $targetDir = Split-Path $targetProfile -Parent

    if (-not (Test-Path $sourceProfile)) {
        Write-GuiLog "Profile source not found: $sourceProfile" -Type Fail
        return $false
    }
    if (-not (Test-Path $sourceModules)) {
        Write-GuiLog "Modules directory not found: $sourceModules" -Type Fail
        return $false
    }

    Write-GuiLog "Linking profile..." -Type Step

    if (Test-Path $targetProfile) {
        $content = Get-Content $targetProfile -Raw -ErrorAction SilentlyContinue
        if ($content -match '\. "[^"]*Microsoft\.PowerShell_profile\.ps1"') {
            Write-GuiLog "Profile already correctly linked." -Type Ok
            return $true
        }

        $timestamp = Get-Date -Format 'yyyyMMdd-HHmmss'
        $backupPath = "$targetProfile.bak-$timestamp"
        if (Test-Path $backupPath) {
            $backupPath = "$targetProfile.bak-$timestamp-$(Get-Random -Maximum 9999)"
        }
        Copy-Item $targetProfile $backupPath -Force
        Write-GuiLog "Existing profile backed up: $backupPath" -Type Info
        Remove-Item $targetProfile -Force
    }

    if (-not (Test-Path $targetDir)) {
        New-Item -ItemType Directory -Force -Path $targetDir | Out-Null
    }

    $poshThemeLine = ''
    if ($ThemeName) {
        $poshThemeLine = "`n`$env:POSH_THEME = `"$ThemeName`""
    }
    $linkContent = "# Generated by config-powershell7 installer`n`$env:__PROFILE_REPO_ROOT = `"$RepoPath`"$poshThemeLine`n. `"$sourceProfile`""
    Set-Content -Path $targetProfile -Value $linkContent -Encoding UTF8 -Force

    $content = Get-Content $targetProfile -Raw -ErrorAction SilentlyContinue
    if ($content -match '\. "[^"]*Microsoft\.PowerShell_profile\.ps1"') {
        Write-GuiLog "Profile linked successfully!" -Type Ok
        return $true
    } else {
        Write-GuiLog "Profile link validation failed." -Type Fail
        return $false
    }
}

function Uninstall-Profile {
    param([string]$RepoPath)

    $targetProfile = Get-ProfilePath

    if (-not $targetProfile) {
        Write-GuiLog "Cannot determine profile path. `$PROFILE is not set." -Type Fail
        return $false
    }

    $targetDir = Split-Path $targetProfile -Parent

    Write-GuiLog "Analyzing current installation..." -Type Step

    if (Test-Path $targetProfile) {
        $content = Get-Content $targetProfile -Raw -ErrorAction SilentlyContinue
        if ($content -match '\. "[^"]*Microsoft\.PowerShell_profile\.ps1"') {
            Write-GuiLog "Found profile created by this project." -Type Ok
            Remove-Item $targetProfile -Force -ErrorAction Stop
            Write-GuiLog "Profile removed." -Type Ok
        } else {
            Write-GuiLog "Profile exists but was NOT created by this project - skipping removal." -Type Warn
        }
    } else {
        Write-GuiLog "No profile found. Nothing to remove." -Type Info
    }

    $backups = @(Get-ChildItem -Path $targetDir -Filter 'Microsoft.PowerShell_profile.ps1.bak*' -ErrorAction SilentlyContinue |
        Sort-Object LastWriteTime -Descending)
    if ($backups.Count -gt 0) {
        Write-GuiLog "Found $($backups.Count) backup file(s)." -Type Info
    }

    Write-GuiLog "Cleaning up cache files..." -Type Step
    $cachePaths = @(
        (Join-Path $HOME '.cache_pwsh_plugins.ps1')
    )
    $xdgCache = if ($env:XDG_CACHE_HOME) { $env:XDG_CACHE_HOME } else { Join-Path $HOME '.cache' }
    $cachePaths += Join-Path (Join-Path $xdgCache 'pwsh') 'plugins_cache.ps1'

    foreach ($cachePath in $cachePaths) {
        if (Test-Path $cachePath) {
            Remove-Item $cachePath -Force -ErrorAction SilentlyContinue
            Write-GuiLog "Cache removed: $cachePath" -Type Ok
        }
    }

    $xdgPwshDir = Join-Path $xdgCache 'pwsh'
    if ((Test-Path $xdgPwshDir) -and (Get-ChildItem $xdgPwshDir -ErrorAction SilentlyContinue).Count -eq 0) {
        Remove-Item $xdgPwshDir -Force -ErrorAction SilentlyContinue
    }

    Write-GuiLog "Uninstallation complete." -Type Ok
    return $true
}
